FROM maven:3.5.2-jdk-8-alpine

ENV WORKSPACE=/usr/src/icm-analytics

# make source folder
RUN mkdir -p $WORKSPACE
WORKDIR $WORKSPACE

# copy sources
COPY pom.xml $WORKSPACE
COPY src $WORKSPACE/src

# run maven to build project
RUN mvn -T 1C install -DskipTests=true
